import '@/app/styles/globals.scss'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import {Header} from "@/components/Header/Header";

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AtOM',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon.png'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header/>
        <main>
            {children}
        </main>
      </body>
    </html>
  )
}
